Анимации слияний (удачных и неудачных).
iobda/folk_alchemy pull request #14
Opened 2024-07-24 14:18 UTC by iobda

Анимация удачного слияния.
Первая версия. Анимация вызывается через ноду merger, которая находится на главной сцене невидимая. Становится видимой только во время слияния и после скрывается. 

Неудачное слияние.
Получаем несовместнимые элементы из game_state и проигрываем анимацию по названию элемента.

Фикс бага с повторным выбором элемента.
Старая не самая правильная система с if-if-else, но надежная и рабочая.

Маленький рефакторинг.
После мерджовый рефакторинг по гдлинту + исправление бага анимации.

2024-07-24 14:48 UTC, Arsen-PhylJoy requested changes
Давай договоримся заворачивать условия в if в круглые скобки, хорошо? Так лучшие считывается код.

2024-07-24 14:48 UTC, Arsen-PhylJoy commented on scenes/main_scene/game_state.gd
> +		Events.failed_merge_elements.emit(_left_element_selected, _right_element_selected)
🙃

2024-07-24 14:48 UTC, Arsen-PhylJoy commented on scenes/merger.gd
> +	Events.left_element.connect(set_left_element)
Можно в отдельную функцию выделить _connect_signals.

2024-07-24 14:48 UTC, Arsen-PhylJoy commented on scenes/merger.gd
> +	await _animation_player.animation_finished
https://www.youtube.com/watch?v=NpoYYJyWWgU&t=528s&ab_channel=PlayWithFurcifer У этих ребят есть опыт больше 10 лет разработки и они выпустили хитовую игру на годот в стим.
Так вот, они рекомендуют отказаться от await/yield и перейти на сигналы, так как так безопаснее. В видео сказано почему не нужно использовать await. (тайминг не нашёл). Так же объясняют то, как заменить await.

2024-07-24 14:48 UTC, Arsen-PhylJoy commented on scripts/autoload/event_bus.gd
> +signal failed_merge_elements(_left_element_selected: String, _right_element_selected: String)
Название сигналов должны быть глаголами в прошедшем времени. Например, что значит "right_element" (можно исправить на "right_element_chosen")??????
Дальше, последний сигнал не нужен. Можно добавить эти аргументы в УЖЕ существующую функцию merge_failed, и там где уже используется обработка данного сигнала просто добавить эти два аргументы с нижним подчёркиванием.
И нет смысла параметры (то есть названия переменных в объявлении функции) писать через нижнее подчёркивание, как на строке 12.

2024-07-24 14:48 UTC, Arsen-PhylJoy commented on scenes/element.gd
> +	Events.failed_merge_elements.connect(fail_merge)
Этот сигнал не нужен

2024-07-24 14:55 UTC, iobda commented on scenes/main_scene/game_state.gd
> +		Events.failed_merge_elements.emit(_left_element_selected, _right_element_selected)
Только из-за того что сигнал уже подвязан к остановке анимации, решил использовать второй сигнал)

2024-07-24 15:10 UTC, iobda commented on scenes/merger.gd
> +	await _animation_player.animation_finished
На 0:17 запрещают использовать в физических процессах и всяких кнопках.
Но на 4:17 используют для анимаций.

2024-07-24 15:29 UTC, Arsen-PhylJoy commented on scenes/main_scene/game_state.gd
> +		Events.failed_merge_elements.emit(_left_element_selected, _right_element_selected)
А почему то, что этот сигнал используется в анимации, мешает его использовать в других местах?

2024-07-24 16:19 UTC, Arsen-PhylJoy commented on scenes/merger.gd
> +	await _animation_player.animation_finished
![image](https://github.com/user-attachments/assets/ed2d0d14-57fe-494d-bac7-c12246b0b644)
Я затестил, память и правда может потеряться, если функция с await не будет выполенена в объекте во время его удаления.

2024-07-25 10:50 UTC, Arsen-PhylJoy requested changes

2024-07-25 10:50 UTC, Arsen-Lovecraft commented on scenes/merger.gd
> +	spawn_popup(folkore_bd_name)
1. Обработать сигнал animation_finished(anim_name:String)
2. if(anim_name == "Merge"): spawn_popup(folkore_bd_name)

2024-07-25 10:50 UTC, Arsen-PhylJoy commented on scenes/element.gd
> +	Events.merge_failed.connect(fail_merge)
```suggestion
	Events.merge_failed.connect(_on_fail_merge)
```

2024-07-25 10:50 UTC, Arsen-PhylJoy commented on scenes/main_scene/game_state.gd
> +	Events.spawn_popup.connect(_spawn_popup_folklore)
Можно в отдельную функцию _connect_signals

2024-07-25 10:50 UTC, Arsen-PhylJoy commented on scenes/main_scene/game_state.gd
> +@onready var merger: Control = %Merger
А эта переменная не должна быть приватной?

2024-07-25 10:50 UTC, Arsen-PhylJoy commented on scripts/autoload/event_bus.gd
> +signal spawn_popup(folkore_bd_name: String)
```suggestion
signal popup_spawned(folkore_bd_name: String)
```

2024-07-25 10:50 UTC, Arsen-PhylJoy commented on scenes/element.gd
> +		_animation_player.play("RESET")
_previous_element = ""
		_animation_player.play("RESET")
		Эти строчки как минимум три раза используются. Я бы отдельную функцию сделал, либо что нибудь ещё придумал. DRY* (Don't repeat yourself)

2024-07-25 11:58 UTC, iobda commented on scripts/autoload/event_bus.gd
> +signal spawn_popup(folkore_bd_name: String)
Блин, я тут не соглашусь... Там именно что прямо сейчас взять и заспавнить попап

2024-07-25 11:59 UTC, iobda commented on scenes/merger.gd
> +	spawn_popup(folkore_bd_name)
Оставлю на будущее)

2024-07-25 12:10 UTC, Arsen-PhylJoy approved these changes
👍

2024-07-25 12:10 UTC, Arsen-PhylJoy commented on scenes/element.gd
> +func clear_animation() -> void:
```suggestion
func _clear_animation() -> void:
```

2024-07-25 12:11 UTC, merged